2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Configure stats pid to 169382
2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Loading settings from /home/icaros/.config/wandb/settings
2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Loading settings from /home/icaros/Documents/PPGADev/wandb/settings
2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-02 21:01:36,189 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-02 21:01:36,190 WARNING MainThread:169382 [wandb_setup.py:_flush():76] Could not find program at -m algorithm.train_ppga
2023-07-02 21:01:36,190 INFO    MainThread:169382 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m algorithm.train_ppga'}
2023-07-02 21:01:36,190 INFO    MainThread:169382 [wandb_init.py:_log_setup():507] Logging user logs to /home/icaros/Documents/PPGADev/wandb/run-20230702_210136-jkczprgy/logs/debug.log
2023-07-02 21:01:36,190 INFO    MainThread:169382 [wandb_init.py:_log_setup():508] Logging internal logs to /home/icaros/Documents/PPGADev/wandb/run-20230702_210136-jkczprgy/logs/debug-internal.log
2023-07-02 21:01:36,190 INFO    MainThread:169382 [wandb_init.py:init():547] calling init triggers
2023-07-02 21:01:36,191 INFO    MainThread:169382 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-02 21:01:36,191 INFO    MainThread:169382 [wandb_init.py:init():596] starting backend
2023-07-02 21:01:36,191 INFO    MainThread:169382 [wandb_init.py:init():600] setting up manager
2023-07-02 21:01:36,205 INFO    MainThread:169382 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-07-02 21:01:36,212 INFO    MainThread:169382 [wandb_init.py:init():606] backend started and connected
2023-07-02 21:01:36,216 INFO    MainThread:169382 [wandb_init.py:init():703] updated telemetry
2023-07-02 21:01:36,267 INFO    MainThread:169382 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-07-02 21:01:36,311 WARNING MainThread:169382 [wandb_init.py:init():1174] interrupted
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 739, in init
    result = run_init_handle.wait(
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-07-02 21:01:39,341 WARNING MsgRouterThr:169382 [router.py:message_loop():77] message_loop has been closed
